spring:
  datasource:
    driver-class-name: org.h2.Driver
    #url: jdbc:h2:tcp://localhost/~/MyTube
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 1234
  h2:
    console:
      enabled: true
  jpa:

    hibernate:
      ddl-auto: create
    properties:
      #hibernate.default_batch_size : 100
      hibernate:
        format_sql : true
        default_batch_fetch_size : 100



  session:
    timeout: 30m

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

logging.level:
  org.hibernate.SQL: debug
  # org.hibernate.type: trace

server:
  servlet:
    session:
      tracking-modes: COOKIE


custom:
  path:
    memberImage: '/Users/neo/Desktop/mtubeFile/images/'
    videos: '/Users/neo/Desktop/mtubeFile/videos/'


