spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/MyTube
    username: sa
    password: 1234
  jpa:

    hibernate:
      ddl-auto: create
    properties:
      hibernate.default_batch_size : 100
      hibernate:
        format_sql : true
        #default_batch_fetch_size : 100



  session:
    timeout: 30m

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

logging.level:
  org.hibernate.SQL: debug
  # org.hibernate.type: trace

server:
  servlet:
    session:
      tracking-modes: COOKIE


custom:
  path:
    memberImage: 'C:\Users\ConyNeo\Desktop\mtubeFile\memberImage\'
    videos: 'C:\Users\ConyNeo\Desktop\mtubeFile\videos\'


